server:
  port: 8090
spring:
  application:
    name: sparing-cloud-gteway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        # Add your routes here.
        - id: aliyun_route
          uri: https://www.aliyun.com/
          predicates:
            - Path=/product/**
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}

        - id: gateway-provider
          uri: lb://gateway-provider
          predicates:
            - Path=/gprovider/**
          filters:
            - StripPrefix=1